### ISSUE TITLE
请问什么时候开源呢

### ISSUE THREAD

**Issue by wangjitoan** [tricktreat/PromptNER#1]
请问什么时候开源呢

**Comment by tricktreat** [comment]
这周末吧，一直没时间整理。

**Comment by wangjitoan** [comment]
jitian.wang
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "tricktreat/PromptNER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月14日(星期三) 晚上9:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tricktreat/PromptNER] 请问什么时候开源呢 (Issue #1)





 
这周末吧，一直没时间整理。
