### ISSUE TITLE
没有找到mit-movie_types.json文件

### ISSUE THREAD

**Issue by wanglu1214** [tricktreat/PromptNER#10]
types_path = data/datasets/few-shot/data/mit-movie/mit-movie_types.json,数据文件中没有找到该mit-movie_types.json文件，不知道是否是我没有找到，能否将该文件下载路径提供给我，谢谢了

**Comment by tricktreat** [comment]
已上传`ner2json.py`到Google云盘里，以转化`.txt`到`.json`。
