### ISSUE TITLE
没有Data的示例

### ISSUE THREAD

**Issue by wangjitoan** [tricktreat/PromptNER#3]
你好，可以公开conll03数据集吗，不胜感激

**Comment by tricktreat** [comment]
你好，CoNLL03数据集：https://drive.google.com/drive/folders/17BXWQ2W0zzrbYR8W1KAWSCNSYJcoUGiw?usp=sharing

**Comment by wangjitoan** [comment]
您好，因为没在论文里看到具体的阐述，想问问您：在训练全量数据集时，比如ACE2005 需要微调Bert的权重吗


jitian.wang
***@***.***



&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "tricktreat/PromptNER"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月12日(星期三) 中午12:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [tricktreat/PromptNER] 没有Data的示例 (Issue #3)





 
你好，CoNLL03数据集：https://drive.google.com/drive/folders/17BXWQ2W0zzrbYR8W1KAWSCNSYJcoUGiw?usp=sharing

**Comment by tricktreat** [comment]
你好，需要的。
