### ISSUE TITLE
动态模板填充

### ISSUE THREAD

**Issue by yulu1998** [tricktreat/PromptNER#4]
请问在进行动态模板填充的时候，M个提示不是一样的吗？那实体和这M个提示之间不同的匹配有什么区别？

**Comment by tricktreat** [comment]
你好，M个提示是不一样的。

**Comment by yulu1998** [comment]
你好，我刚接触这方面不久，所以可理解为：因为使用软模板，所以M个提示是不一样的。是吗？不胜感激

**Comment by tricktreat** [comment]
> 你好，我刚接触这方面不久，所以可理解为：因为使用软模板，所以M个提示是不一样的。是吗？不胜感激

不是的，模板中的每个slot都是不同的token，我们用的是bert中的`[unused1]-[unused100]`以及一些`rare tokens`，因此构造出的提示也是不一样的。
