### ISSUE TITLE
有关代码中数据的问题。

### ISSUE THREAD

**Issue by lDAIZzzl** [tricktreat/PromptNER#6]
您好，请问论文代码中wiki_50000_80_first_types.json现在可以下载吗，想复现一下论文中的实验

**Comment by tricktreat** [comment]
Sorry, 遗漏了文件。现在已上传

**Comment by lDAIZzzl** [comment]
还想请问一下conll03_train.json以及conll03_dev.json可以下载吗？

**Comment by tricktreat** [comment]
@lDAIZzzl  Hi, 已上传。请查看最新commit。

**Comment by lDAIZzzl** [comment]
非常感谢您的回复，我还有有关数据集的问题，就是In-/Cross-domain data中ATIS, MIT-Restaurant以及MIT-Movie的json文件可以下载吗？

**Comment by tricktreat** [comment]
@lDAIZzzl 你好，这个可以自己写个conll2json的脚本转化一下

**Comment by lDAIZzzl** [comment]
想请教一下conll2003以及wiki数据集转化的json中的org_id，ltokens以及rtokens是什么意思呢？In-/Cross-domain data中的数据是否应该对照conll2003的格式转化数据？

**Comment by tricktreat** [comment]
@lDAIZzzl 可以全部置为空，org_id="", ltokens=[], rtokens=[]。
