### ISSUE TITLE
How do I get the JSON file

### ISSUE THREAD

**Issue by T00ler** [tricktreat/PromptNER#7]
Hi, I want to know how to get the JSON file.
The uploaded file is in txt format, but it seems that the source code needs to be converted to JSON format before it can be used. And 'mit-movie_types.json' is also not in the dataset. However, no tool class for conversion was found in the source code.

**Comment by wanglu1214** [comment]
mit-movie_types.json文件不在数据集中，这个问题你最终是如何解决的呀

**Comment by T00ler** [comment]
> mit-movie_types.json文件不在数据集中，这个问题你最终是如何解决的呀

作者只提供了txt文件，你可能得自己写一个方法给他转成作者要求的json格式的样子。

**Comment by tricktreat** [comment]
已上传`ner2json.py`到Google云盘里，以转化`.txt`到`.json`。

> mit-movie_types.json文件不在数据集中，这个问题你最终是如何解决的呀
