### ISSUE TITLE
关于eval方法

### ISSUE THREAD

**Issue by T00ler** [tricktreat/PromptNER#8]
训练几个epoch后会使用验证集进行验证，那个效果看着是正常的，但是训练完毕后使用eval方法进行测试后效果低的离谱，读了代码发现尽管验证和测试集是同一个，但是测试出来的效果不知道为什么特别低。

**Comment by scuyzm1** [comment]
打扰了，请问你的问题解决了吗

**Comment by scuyzm1** [comment]
> 训练几个epoch后会使用验证集进行验证，那个效果看着是正常的，但是训练完毕后使用eval方法进行测试后效果低的离谱，读了代码发现尽管验证和测试集是同一个，但是测试出来的效果不知道为什么特别低。

打扰了，请问你的问题解决了吗

**Comment by T00ler** [comment]
> > 训练几个epoch后会使用验证集进行验证，那个效果看着是正常的，但是训练完毕后使用eval方法进行测试后效果低的离谱，读了代码发现尽管验证和测试集是同一个，但是测试出来的效果不知道为什么特别低。
> 
> 打扰了，请问你的问题解决了吗

还没，我后面试了一下在训练的过程中预载入已经训练好的模型权重进行训练，发现一个问题，就是在刚开始的epoch里面验证效果也是很低的，尽管他能更快收敛。总之挺奇怪的和我想象的都不大一样就没研究了。
